# Smaller image: slim base + no cache
FROM python:3.11-slim

WORKDIR /app

COPY requirements-docker.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=1000 -r requirements-docker.txt

COPY . .

CMD ["python", "training/train.py"]
